version: '3.8'

services:
  #Servicio correspondiente a la bd mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: mysqlpass
    networks:
      - back-tier
  #Servicio correspondiente al backend de la app
  api:
    image: 127.0.0.1:5000/backend:1.0.0
    hostname: apihost
    ports:
      - 3030:3030
    environment:
      PORT: 3030
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: movie_db
    depends_on:
      - mysql
    networks:
      - back-tier
    deploy:
      replicas: 2
  #Servicio correspondiente al frotnend de la app
  webapp:
    image: 127.0.0.1:5000/frontend:1.0.0
    ports:
      - 8080:3000
    environment:
      PORT: 3000
      BACKEND_URL: apihost:3030
    networks:
      - front-tier
      - back-tier
    deploy:
      placement:
        replicas: 2
        max_replicas_per_node: 1
networks:
  front-tier: {}
  back-tier: {}

