Vagrant.configure("2") do |config|

	config.vm.box = "geerlingguy/centos7"

	#Se comenta esta linea del archivo original
	#config.vm.network "public_network"
	
	#Se agrega esta linea donde ya se define la interfaz especifica (la que se va a utilizar en mi pc)
	#Se realiza este cambio con el objetivo que vagrant no la pida al realizar el up
	config.vm.network "public_network", bridge: "en0: Wi-Fi"

	config.vm.define "monitoring1" do |monitoring1|

		#Se define un hostname para la VM
		monitoring1.vm.hostname = "monitoring1"

		#Se comenta esta linea ya que por defecto este rango de IP no esta habilitado para mi red
		#monitoring1.vm.network "private_network", ip: "10.20.30.3"
		
		#Se agrega esta linea (con una IP valida) para asignarle una ip a la vm
		monitoring1.vm.network "private_network", ip: "192.168.56.103"

		monitoring1.vm.provision "shell", path: "provision/provision.sh"
		monitoring1.vm.provision "shell", path: "provision/provision_target.sh"

		monitoring1.vm.synced_folder ".", "/vagrant"

		monitoring1.vm.provider "virtualbox" do |vb|
			vb.memory = 1024
			vb.cpus = 1
			vb.name = "monitoring1"
		end

	end

	config.vm.define "monitoring2" do |monitoring2|

		#Se define un hostname para la VM
		monitoring2.vm.hostname = "monitoring2"

		#Se comenta esta linea ya que por defecto este rango de IP no esta habilitado para mi red
		#monitoring1.vm.network "private_network", ip: "10.20.30.4"
		
		#Se agrega esta linea (con una IP valida) para asignarle una ip a la vm
		monitoring2.vm.network "private_network", ip: "192.168.56.104"

        monitoring2.vm.provision "shell", path: "provision/provision.sh"
		monitoring2.vm.provision "shell", path: "provision/provision_prome.sh"

		monitoring2.vm.synced_folder ".", "/vagrant"

		monitoring2.vm.provider "virtualbox" do |vb|
			vb.memory = 2048
			vb.cpus = 2
			vb.name = "monitoring2"
		end

	end
	
end