---

#Esta play se ejecuta en localhost (Ansible Master o nodo1)
#Agrega los nodos 2 y 3 al archivo know_hosts del nodo1 para poder conectarse por ssh sin inconvenientes
- hosts: localhost
  connection: local
  tasks:
    - { debug: { msg: "Esta tarea corre local" } }  
    - name: add repo keys
      ansible.builtin.shell:
        cmd: ssh-keyscan -H 192.168.56.101 >> ~/.ssh/known_hosts && ssh-keyscan -H 192.168.56.102 >> ~/.ssh/known_hosts

#Play encargada de ejecutar los roles que installan y levantan consul en el nodo 2 y 3
- hosts: all
  roles:
    - install_consul
    - setting_up_consul

  
