# -*- mode: ruby -*-
# vi: set ft=ruby :

#Mediante este archivo de configuracion de vagrant vamos a crear 3 VM
#nodo1: Ansible Master
#nodo2: Consul server
#nodo3: Consul client


servers=[
  {:hostname => "nodo1",:ip => "192.168.56.100",:script => " /vagrant/config_nodos/nodo1/bootstrap_nodo1.sh"},
  {:hostname => "nodo2",:ip => "192.168.56.101",:script => " /vagrant/config_nodos/nodo2/bootstrap_nodo2.sh"},
  {:hostname => "nodo3",:ip => "192.168.56.102",:script => " /vagrant/config_nodos/nodo3/bootstrap_nodo3.sh"}
]

# Take the hostname of the last machine in the array
last_vm = servers[(servers.length) -1][:hostname]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|

            # ----- Configuracion comun a los 3 nodos ----- #
            node.vm.box = "ubuntu/bionic64"
            node.vm.box_version = "20220916.0.0"
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
          
            $script = "/bin/bash --login #{machine[:script]}"
            node.vm.provision :shell, privileged: false, inline: $script   
            
            node.vm.provider "virtualbox" do |v|
              # Definimos la memoria asignada a la VM (2GB en este caso)
              v.memory = "2048"
              v.name = machine[:hostname]
            end            

            # $scriptTrigger = "/bin/bash --login config_nodos/post_provision.sh"

            # # ----- Trigger -> Solo se ejecuta luego de que levanta la ultima VM ------ #
            # node.trigger.after :up do |trigger|
            #     trigger.only_on = last_vm  # <---- Se dispara cuando el nodo3 esta arriba!
            #     trigger.info = "!!!! Disparando trigger post up de todos los nodos !!!!"
            #     trigger.run = {inline: "chmod +x config_nodos/post_provision.sh"}
            #     #trigger.run = {path: "config_nodos/post_provision.sh", privileged: false}
            #     trigger.run = {inline: $scriptTrigger, privileged: false}
            # end
        end
    end
end



# # Define la version del archivo que vamos a utilizar
# # Esto generalmente no se toca
# Vagrant.configure("2") do |config|


#   # Se define la configuracion del nodo1 - Ansible Master
#   config.vm.define "nodo1" do |nodo1|
    
#     # Seleccionamos la imagen de la VM que queremos utilizar
#     # En este caso corresponde a una imagen de Ubuntu 18.04 LTS
#     # Mediante el tag config.vm.box_version tambien podemos definir una version especifica de la imagen
#     # Por mas imagenes visitar https://vagrantcloud.com/search
#     nodo1.vm.box = "ubuntu/bionic64"
#     nodo1.vm.box_version = "20220916.0.0"

#     #Se define un hostname para la VM
#     nodo1.vm.hostname = "nodo1"

#     #Configuracion del port forwarding entre host y guest
#     #nodo1.vm.network :forwarded_port, guest: 22, host: 22

#     #Defino una private_network y le asigno una ip al nodo1
#     #La ip debe estar en el rango: Ranges: 192.168.56.0/21
#     nodo1.vm.network :private_network, ip: "192.168.56.100"

#     # Se define el script bootstrap_nodo1.sh para provisionar la VM
#     # Se le pasa la opcion privileged: false para que el script se corra con el usuario vagrant y no con root
#     # Esto ultimo es para que la clave ssh se cre con el usuario vagrant
#     $script = "/bin/bash --login /vagrant/config_nodos/nodo1/bootstrap_nodo1.sh"
#     nodo1.vm.provision :shell, privileged: false, inline: $script

#     #nodo1.vm.provision :shell, path: "config_nodos/nodo1/bootstrap_nodo1.sh", privileged: false

#     # Configuracion especifica del provider. En nuestro caso, Virtualbox
#     nodo1.vm.provider "virtualbox" do |v|
#       # Definimos la memoria asignada a la VM (2GB en este caso)
#       v.memory = "2048"
#       v.name = "nodo1"
#     end

#   end

#   # Se define la configuracion del nodo2 - Consul Server
#   config.vm.define "nodo2" do |nodo2|

#     # Seleccionamos la imagen de la VM que queremos utilizar
#     # En este caso corresponde a una imagen de Ubuntu 18.04 LTS
#     # Mediante el tag config.vm.box_version tambien podemos definir una version especifica de la imagen
#     # Por mas imagenes visitar https://vagrantcloud.com/search
#     nodo2.vm.box = "ubuntu/bionic64"
#     nodo2.vm.box_version = "20220916.0.0"

#     #Se define un hostname para la VM
#     nodo2.vm.hostname = "nodo2"

#     #Configuracion del port forwarding entre host y guest
#     #nodo2.vm.network :forwarded_port, guest: 22, host: 22

#     #Defino una private_network y le asigno una ip al nodo2
#     #La ip debe estar en el rango: Ranges: 192.168.56.0/21
#     nodo2.vm.network :private_network, ip: "192.168.56.101"

#     # Se define el script bootstrap.sh (en el mismo dir que el archivo de vagrant) para provisionar la VM
#     nodo2.vm.provision :shell, path: "config_nodos/nodo2/bootstrap_nodo2.sh"

#     # Configuracion especifica del provider. En nuestro caso, Virtualbox
#     nodo2.vm.provider "virtualbox" do |v|
#       # Definimos la memoria asignada a la VM (2GB en este caso)
#       v.memory = "2048"
#       v.name = "nodo2"
#     end
#   end

#    # Se define la configuracion del nodo3 - Consul Client
#    config.vm.define "nodo3" do |nodo3|
    
#     # Seleccionamos la imagen de la VM que queremos utilizar
#     # En este caso corresponde a una imagen de Ubuntu 18.04 LTS
#     # Mediante el tag config.vm.box_version tambien podemos definir una version especifica de la imagen
#     # Por mas imagenes visitar https://vagrantcloud.com/search
#     nodo3.vm.box = "ubuntu/bionic64"
#     nodo3.vm.box_version = "20220916.0.0"

#     #Se define un hostname para la VM
#     nodo3.vm.hostname = "nodo3"

#     #Configuracion del port forwarding entre host y guest
#     #nodo3.vm.network :forwarded_port, guest: 22, host: 22

#     #Defino una private_network y le asigno una ip al nodo3
#     #La ip debe estar en el rango: Ranges: 192.168.56.0/21
#     nodo3.vm.network :private_network, ip: "192.168.56.102"

#     # Se define el script bootstrap.sh (en el mismo dir que el archivo de vagrant) para provisionar la VM
#     nodo3.vm.provision :shell, path: "config_nodos/nodo3/bootstrap_nodo3.sh"

#     # Configuracion especifica del provider. En nuestro caso, Virtualbox
#     nodo3.vm.provider "virtualbox" do |v|
#       # Definimos la memoria asignada a la VM (2GB en este caso)
#       v.memory = "2048"
#       v.name = "nodo3"
#     end
#   end
  
# end
