# -*- mode: ruby -*-
# vi: set ft=ruby :

#Mediante este archivo de configuracion de vagrant vamos a crear 3 VM
#nodo1: Ansible Master
#nodo2: Consul server
#nodo3: Consul client

#Se define un arreglo con propiedades para cada uno de los 3 nodos
servers=[
  {:hostname => "nodo1",:ip => "192.168.56.100",:script => " /vagrant/config_nodos/nodo1/bootstrap_nodo1.sh"},
  {:hostname => "nodo2",:ip => "192.168.56.101",:script => " /vagrant/config_nodos/nodo2/bootstrap_nodo2.sh"},
  {:hostname => "nodo3",:ip => "192.168.56.102",:script => " /vagrant/config_nodos/nodo3/bootstrap_nodo3.sh"}
]


Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|

            # ----- Configuracion comun a los 3 nodos ----- #
            node.vm.box = "ubuntu/bionic64"
            node.vm.box_version = "20220916.0.0"
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
          
            #Se configura el scritp que se va a ejecutar en cada nodo con config inicial
            $script = "/bin/bash --login #{machine[:script]}"
            node.vm.provision :shell, privileged: false, inline: $script   
            
            node.vm.provider "virtualbox" do |v|
              # Definimos la memoria asignada a la VM (2GB en este caso)
              v.memory = "2048"
              v.name = machine[:hostname]
            end            
        end
    end
end